apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: guestbook
  source:
    path: helm-guestbook
    repoURL: https://github.com/chen-keinan/argocd-example-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=true
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
